apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "octoprint.fullname" . }}-startup
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
{{ include "octoprint.labels" . | indent 4 }}
data:
  run: |
    #!/usr/bin/with-contenv sh

    exec octoprint serve --iknowwhatimdoing --host 0.0.0.0 --port 5000 --basedir /octoprint/octoprint --overlay /octoprint/config.overlay.yaml