name: Release Helm Chart

on:
  push:
    branches:
      - master
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Create chart package
        run: |
          mkdir -p .deploy
          helm package . -d .deploy

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy chart and rebuild index
        run: |
          cp .deploy/*.tgz gh-pages/
          cd gh-pages
          helm repo index . --url https://arbuzov.github.io/octoprint
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Helm chart"
          git push origin gh-pages
