name: Release Helm Chart

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Lint chart
        run: helm lint .

      - name: Create chart package
        run: |
          mkdir -p .deploy
          helm package . -d .deploy

      - name: Prepare gh-pages branch
        run: |
          git fetch origin gh-pages || true
          git worktree add gh-pages gh-pages || git worktree add gh-pages -b gh-pages

      - name: Copy chart package
        run: cp .deploy/*.tgz gh-pages/

      - name: Regenerate repository index
        run: |
          cd gh-pages
          helm repo index . --url https://arbuzov.github.io/octoprint

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Helm chart"
          git push origin gh-pages
