name: Release Helm Chart

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Install helm-docs
        run: |
          mkdir -p /tmp/helm-docs
          curl -L https://github.com/norwoodj/helm-docs/releases/download/v1.13.1/helm-docs_1.13.1_Linux_x86_64.tar.gz | tar -xz -C /tmp/helm-docs
          install /tmp/helm-docs/helm-docs /usr/local/bin/helm-docs
          rm -rf /tmp/helm-docs

      - name: Lint chart
        run: helm lint .

      - name: Generate README
        run: helm-docs

      - name: Create chart package
        run: |
          mkdir -p .deploy
          helm package . -d .deploy

      - name: Prepare gh-pages branch
        run: |
          git fetch origin gh-pages || true
          git worktree add gh-pages gh-pages || git worktree add gh-pages -b gh-pages

      - name: Copy chart package
        run: cp .deploy/*.tgz gh-pages/

      - name: Regenerate repository index
        run: |
          cd gh-pages
          helm repo index . --merge index.yaml --url https://arbuzov.github.io/octoprint

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --quiet --cached; then
            git commit -m "Update Helm chart"
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi
