name: Validate Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint chart
        run: helm lint .
      - name: Template chart
        run: helm template . --values values.yaml --output-dir output

